auto: true

markdown: rdiscount
rouge: true
paginate: 8
permalink: /:title

title: Alvin's Boat
url: http://cidisk.github.io
feed: /atom.xml
author_info: <a href="http://cidisk.github.io">cidisk</a>


name: Alvin's Boat
description: Tech blog for cidisk@163.com
url: http://cidisk.github.io
