auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: Alvin's Ship
url: http://cidisk.github.io
feed: /atom.xml
author_info: <a href="http://cidisk.github.io">cidisk</a>


name: Alvin's Ship
description: Tech blog for cidisk@163.com
url: http://cidisk.github.io